[project]
name = "build-an-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
]
